<registration-component
        email-label="{{ __('EMAIL') }}"
        email-invalid-feedback="{{ __('Please provide a valid email address') }}"
        title-label="{{ __('TITLE') }}"
        title-invalid-feedback="{{ __('Please select a title') }}"
        first-name-label="{{ __('FIRST NAME') }}"
        first-name-invalid-feedback="{{ __('Please provide a first name') }}"
        last-name-label="{{ __('LAST NAME') }}"
        last-name-invalid-feedback="{{ __('Please provide a last name') }}"
        mobile-label="{{ __('MOBILE') }}"
        mobile-invalid-feedback="{{ __('Please provide a valid telephone number') }}"
        postcode-label="{{ __('POSTCODE') }}"
        postcode-invalid-feedback="{{ __('Please provide a valid Australian postcode') }}"
        date-of-birth-label="{{ __('DATE OF BIRTH') }}"
        date-of-birth-invalid-feedback="{{ __('Please provide a valid date of birth') }}"
        password-label="{{ __('PASSWORD') }}"
        password-invalid-feedback="{{ __('Please provide a password') }}"
        accept-terms-label="{{ __('I agree to terms of use') }}"
        accept-terms-invalid-feedback="{{ __('Please agree to accept the terms') }}"
        register-button-label="{{ __('REGISTER') }}"
        :title-options="[{value: null,text:'select title'},'Mr','Ms','Mrs','Dr']"
        password-hide-label="{{__('hide')}}"
        password-show-label="{{__('show')}}"
></registration-component>